version: '3.9'

services:
  app:
    build: .
    container_name: todo-api
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis
      - todo-gress

  redis:
    image: redis:alpine

  todo-gress:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres_db-data:/var/lib/postgresql/data/

